# This is a basic workflow to help you get started with Actions

name: Generate PDF

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # If previous build is still running this will cancel it.  
  cancel_previous_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
   
   
  generate:
    runs-on: ubuntu-latest
    
    # If build doesn't succed in 10 minutes there must be something wrong. I guess.
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2

      - name: Run latexmk
        uses: v3lop5/latex-action@thin
        with:
          root_file: master.tex

      - name: Get current date
        id: date
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 1
          format: 'YYYY-MM-DD'
          
      - name: Upload master.pdf as release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: master.pdf
          asset_name: "${{ steps.date.outputs.time }}_${{ github.event.repository.name }}.pdf"
          tag: ${{ steps.date.outputs.time }}
          release_name: "Release ${{ steps.date.outputs.time }}"
          overwrite: true
          body: "Generated master.pdf on ${{ steps.date.outputs.time }}. Will contain the latest version of this day. I'm pretty sure"
